### PR TITLE
Cdns phy torrent v2

### PR DESCRIPTION
**Pull request by yamonkarcdns**
- Renamed cadence dp phy driver to torrent phy.
- Renamed dp phy terms in cadence phy driver, j721e-wiz, k3-j721e-main and documentation to torrent phy
- Updated Kconfig option in audio_display.cfg file to  from CONFIG_PHY_CADENCE_DP to
CONFIG_PHY_TORRENT.

### CODE REVIEW

**Comment by tomba** [comment]
All the travis checks fail as the module filename is changed here.
Can you create a commit to change the .travis.yml to refer to the new .ko instead of phy-cadence-dp.ko, and push it to this same branch. That should fix travis.

**Review by tomba — APPROVED** [review]
Looks good to me

**Comment by sjakhadecdns** [comment]
Can we merge this pull request if TI is okay with the changes, so that we can create new pull request on top of this for regmap changes?

**Review by jsarha — APPROVED** [review]
checkpatch.pl --strict reports some alignment issues, but I guess those are not that serious. So approved.

**Pull request merged**
